- name: updating route53 records
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0caa92da7b80302bc
    zone_id: "Z0732355102QE6GB8XDYY"
    domain_name: "sgrdevsecops.fun"
    instances:
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: print public_ip
    ansible.builtin.debug: "{{ item.instances[0].public_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: print private_ip
    ansible.builtin.debug: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"
